spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8888"
server:
  port: 8789

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/