spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8888"    
server:
  port: 8886

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8887/eureka/